name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  GITHUB_TOKEN:  # id of input
    description: 'Github token'
    required: true
  PUSHED_GITHUB_SHA:  # id of input
    description: 'Github sha commit'
    required: true    
runs:
  using: 'node20'
  main: 'index.js'
