name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  GITHUB_TOKEN:  # id of input
    description: 'Github token'
    required: true
  PUSHED_GITHUB_SHA:  # id of input
    description: 'Github sha commit'
    required: true    
  GITHUB_BRANCH:
    description: "Github branch"
    required: true
  COVERALLS_REPO_TOKEN:
    description: "Coveralls repo token"
    required: true
  COVERALLS_URL:
    description: "Coveralls URL"
    required: true
  PR_NUMBER:
    description: "PR number"
    required: true
  COVERAGE_PLATFORM_TOKEN:
    description: "Coverage platform token"
    required: true
runs:
  using: 'node20'
  main: 'index.js'
